INSERT INTO PUBLIC.BOOK_GENRE (GENRE_NAME) VALUES ('Fantasy');
INSERT INTO PUBLIC.BOOK_GENRE (GENRE_NAME) VALUES ('Science Fiction');
INSERT INTO PUBLIC.BOOK_GENRE (GENRE_NAME) VALUES ('Mystery');

INSERT INTO PUBLIC.BOOK (BOOK_GENRE_ID, NAME, AUTHOR, PRICE) VALUES (1, 'A Game of Thrones', 'George RR Martin', 60.00);
INSERT INTO PUBLIC.BOOK (BOOK_GENRE_ID, NAME, AUTHOR, PRICE) VALUES (2, '1984', 'George Orwwll', 35.00);
INSERT INTO PUBLIC.BOOK (BOOK_GENRE_ID, NAME, AUTHOR, PRICE) VALUES (3, 'Murder on the Orient Express', 'Agatha Christie', 50.00);

INSERT INTO PUBLIC.CUSTOMER (FIRST_NAME, LAST_NAME, PHONE) VALUES ('John', 'Smith', '555666333');
INSERT INTO PUBLIC.CUSTOMER (FIRST_NAME, LAST_NAME, PHONE) VALUES ('Jane', 'Doe', '111222333');

INSERT INTO PUBLIC.SALE (BOOK_ID, CUSTOMER_ID, SALE_DATE, SALE_PRICE) VALUES (1, 1, '2025-07-01', 60.00);
INSERT INTO PUBLIC.SALE (BOOK_ID, CUSTOMER_ID, SALE_DATE, SALE_PRICE) VALUES (2, 1, '2025-07-08', 35.00);
INSERT INTO PUBLIC.SALE (BOOK_ID, CUSTOMER_ID, SALE_DATE, SALE_PRICE) VALUES (3, 2, '2025-07-07', 50.00);
